### ISSUE TITLE
Support for ingress?

### ISSUE THREAD

**Issue by nodesocket** [kubetail-org/helm#1]
Any plans to support an ingress?

Configuration block could look like:

```yaml
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
  hosts:
    - host: kubetail.mydomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - kubetail.mydomain.com
```
